baseURL = "https://anakamran.netlify.app/"
languageCode = "en-us"
title = "welcome"
theme = "archie"
copyright = "Â© Ana Kamran"

[pagination]
  pagerSize = 3

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[params]
  mode = "toggle"
  useCDN = false
  subtitle = ""
  customcss = ["css/first.css"]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kamranana"

[[menu.main]]
name = "home"
url = "/"
weight = 1

[[menu.main]]
name = "course reviews"
url = "/everything"
weight = 3

[[menu.main]]
name = "about"
url = "/about"
weight = 2

[[menu.main]]
name = "books"
url = "/books"
weight = 4

[[menu.main]]
name = "cybersecurity"
url = "/cybersecurity"
weight = 5

[[menu.main]]
name = "cs-progress"
url = "/cs-progress"
weight = 6

[[menu.main]]
name = "blog"
url = "/blog"
weight = 7



